### ISSUE TITLE
Can you add TabbedViewNavigatorTabBar Skin?

### ISSUE THREAD

**Issue by leossmith** [quick6black/flex-Android-Material-Skins#3]
Bottom navigation is again a thing in Android so this would be perfect.

https://material.io/guidelines/components/bottom-navigation.html

**Comment by quick6black** [comment]
I have the tabbednavigator skinned, just working out some issues with height and how the Icon is positioned.

**Comment by quick6black** [comment]
added in the tabbedviewnavigator. I will add in some examples later.

**Comment by quick6black** [comment]
just updated the repo, review the project to look at how to fade between tabs, and use swipe gestures to hide and unhide the tab and actionbar.
