### ISSUE TITLE
Can you please skin the MobileGrid

### ISSUE THREAD

**Issue by leossmith** [quick6black/flex-Android-Material-Skins#4]
A material MobileGrid would be great for mobile projects. If you could add a skin like this:

https://material.io/guidelines/components/data-tables.html

it would be awesome.

**Comment by quick6black** [comment]
i can probably have something next week

**Comment by leossmith** [comment]
Hi there, do you have any update? Thank you.

**Comment by quick6black** [comment]
update, some of the component will need to be rewritten to properly replicate the material design. I did as much as I could with the skin

**Comment by quick6black** [comment]
did another update to add in new sort icons and change the header height.

**Comment by leossmith** [comment]
Awesome. Thanks 👍
