### ISSUE TITLE
Numeric Stepper

### ISSUE THREAD

**Issue by joyola** [quick6black/flex-Android-Material-Skins#5]
Is it possible to include NumericStepper in the list of components?

Thanks for your job. Its fantastic!

**Comment by quick6black** [comment]
thanks, I can work on that. Do you have an example you want to replicate?

**Comment by joyola** [comment]
<img width="287" alt="screen shot 2017-03-10 at 13 47 06" src="https://cloud.githubusercontent.com/assets/4267418/23804281/1e16e01e-0598-11e7-815a-74c8e19aabc8.png">

**Comment by quick6black** [comment]
added in numeric stepper skins. I used a chevron instead of a triangle because i had the path code readily available. Tried to make it as light weight as possible. Make sure you look at the changes in stagedtextskinbase as well.
