### ISSUE TITLE
Textinput skin different than StageTextInput

### ISSUE THREAD

**Issue by leossmith** [quick6black/flex-Android-Material-Skins#6]
Hi, it looks like textinput (and textarea) skin are different from StageText. The skin looks like older android, version 4. Can you update it?

Thank you.

**Comment by quick6black** [comment]
updated textinput, also updated the CSS and View1 to show how to use each by changing the stylename

**Comment by leossmith** [comment]
That was fast. Awesome work 👍

**Comment by quick6black** [comment]
thanks, it was a simple fix
