### ISSUE TITLE
How to change the gap between Input and line?

### ISSUE THREAD

**Issue by leossmith** [quick6black/flex-Android-Material-Skins#7]
I am trying to change the gap between the textInput input and the line

![image](https://user-images.githubusercontent.com/4300876/39635920-7c246db4-4fc7-11e8-9c52-0a18a2710395.png)

Can you help me?

**Comment by neminovno** [comment]
What is your current code?

**Comment by quick6black** [comment]
<s:TextInput prompt="TextInput" paddingBottom="0"/>
