### ISSUE TITLE
TabNavigator gradient

### ISSUE THREAD

**Issue by leossmith** [quick6black/flex-Android-Material-Skins#9]
I am trying to make a gradient color tab navigator but something doesn't work as I think it should. This is what I get:

![image](https://user-images.githubusercontent.com/4300876/42419943-cce8815e-82c6-11e8-90ed-4dbab9dec882.png)

but the gradient should be spread to the whole width.

This is the alternation I did in the TabbedViewNavigatorTabBarSkin:

`
override protected function drawBackground(unscaledWidth:Number, unscaledHeight:Number):void
    {
        super.drawBackground(unscaledWidth, unscaledHeight);

        // backgroundAlpha style is not supported by ButtonBar
        // TabbedViewNavigatorSkin sets a hard-coded value to support
        // overlayControls
        var backgroundAlphaValue:* = getStyle("backgroundAlpha");
        var backgroundAlpha:Number = (backgroundAlphaValue === undefined)
            ? 1 : getStyle("backgroundAlpha");
        
        //graphics.beginFill(getStyle("chromeColor"), 0);
		graphics.beginGradientFill(GradientType.LINEAR,[0x120CCA,0xBB00D1], 
			[1,1],
			[0, 255], 
			null,
			SpreadMethod.PAD);
        graphics.drawRect(0, 0, unscaledWidth, unscaledHeight);
        graphics.endFill();
    }
`

Can you help me find out what is wrong?

Is it possible to maybe change the TabNavigator to an image?

Thanks.

**Comment by quick6black** [comment]
import flash.display.GradientType;
   import mx.core.mx_internal;

   use namespace mx_internal;   

 override protected function drawBackground(unscaledWidth:Number, unscaledHeight:Number):void
    {
        super.drawBackground(unscaledWidth, unscaledHeight);

		colorMatrix.createGradientBox(unscaledWidth, unscaledHeight, Math.PI /2,0,0);
		graphics.beginGradientFill(GradientType.LINEAR, [0x120CCA,0xBB00D1], [1,1],[0, 255],colorMatrix);
		graphics.drawRect(0, 0, unscaledWidth, unscaledHeight);
		graphics.endFill();
    }

**Comment by quick6black** [comment]
the old actionbar component used a gradient color, which is very similar to what you were looking for. The old tabbedViewNavigator component used images for the buttons. 

https://github.com/apache/flex-sdk/blob/master/frameworks/projects/mobiletheme/src/spark/skins/mobile/TabbedViewNavigatorTabBarFirstTabSkin.as

you could look at that for a start.

**Comment by leossmith** [comment]
Can you help me with changing the size of the tab bar? Is there a way to set the ButtonBarSkin height in

`measuredWidth = dataGroup.measuredWidth;
        measuredHeight = dataGroup.measuredHeight;
`
via CSS or another way? If I hardcode it it works, but I don't think this is the best option. 

The left is what I currently have. The right is what I am trying to achieve

![image](https://user-images.githubusercontent.com/4300876/42567953-1e300f9c-8514-11e8-8452-a7aa521321b1.png)

I need some help to understand how to change the size the overall size of tabbar and icons.

Thank you.

**Comment by quick6black** [comment]
I had actually worked on this a while ago and never merged it in, see if this will work. 

I added in tabbedViewNavigatorSkin, here is the link to the .as file 
https://github.com/quick6black/flex-Android-Material-Skins/blob/master/src/spark/skins/android5/TabbedViewNavigatorSkin.as

there is also one addition to the CSS file. In the skin file you can change the height of the tab bar and the button heights will update to match. Let me know if you have any issues

**Comment by leossmith** [comment]
I will try it and let you know. I am building an awesome new app and your skins make flex really shine.

**Comment by quick6black** [comment]
awesome, looking forward to seeing some screenshots of the UI
